FROM ubuntu:24.10

RUN sed -i 's/deb/deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get build-dep --yes python-apt
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes python3-wheel python3-venv python3-build
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes curl
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY build.sh /build.sh

ENTRYPOINT ["/build.sh"]
