name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Jammy wheel
        uses: ./build-jammy
      - name: Build Noble wheel
        uses: ./build-noble
      - name: Build Oracular wheel
        uses: ./build-oracular
      - uses: actions/upload-artifact@v4
        with:
          name: "wheels"
          path: "*.whl"
