name: build
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64, ppc64le, riscv64, s390x]
        series: [jammy, noble, oracular]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup qemu
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Build wheels
        run: |
          make ARCH=${{ matrix.arch }} SERIES=${{ matrix.series }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.series }}-${{ matrix.arch }}
          path: "*.whl"

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: |
          gh release create $(date -I)-${{ github.job }} *.whl
